package claude

import (
	"context"
	"fmt"
	"math/rand/v2"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestClassifyCurrencyName(t *testing.T) {
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		t.Fatal("ANTHROPIC_API_KEY environment variable is required")
	}

	client := NewClient(apiKey)
	ctx := context.Background()

	tests := []struct {
		category            string
		includeRandomSuffix bool
		inputs              []string
	}{
		{
			category: "cryptocurrency",
			inputs: []string{
				"Bitcoin",
				"Ethereum",
				"Solana",
				"Dogecoin",
				"Litecoin",
				"Cardano",
				"Ripple",
				"Polkadot",
				"Avalanche",
				"Chainlink",
				"Monero",
				"Zcash",
				"Tron",
				"Stellar",
				"Tezos",
				"Algorand",
				"Cosmos",
				"NEAR Protocol",
				"Aptos",
				"Sui",
				"Filecoin",
				"Hedera",
				"Shiba Inu",
				"PEPE",
				"BONK",
				"FLOKI",
				"Uniswap",
				"Arbitrum",
				"Optimism",
				"XRP",
				"BNB",
				"Polygon",
				"MATIC",
				"WBTC",
				"wBTC",
			},
		},
		{
			category:            "exchange_platform",
			includeRandomSuffix: true,
			inputs: []string{
				"Coinbase",
				"Binance",
				"Kraken",
				"Robinhood",
				"Gemini Exchange",
				"Bitfinex",
				"Bybit",
				"OKX",
				"Crypto.com",
				"eToro",
				"KuCoin",
				"Huobi",
				"Gate.io",
				"MEXC",
				"Bitstamp",
				"BitMEX",
				"Upbit",
				"Bithumb",
				"FTX",
				"Poloniex",
				"LocalBitcoins",
				"Coinmama",
				"Bittrex",
				"dYdX",
				"PancakeSwap",
			},
		},
		{
			category: "fiat_currency",
			inputs: []string{
				"Dollar",
				"Euro",
				"Yen",
				"Pound Sterling",
				"Peso",
				"Franc",
				"Rupee",
				"Korean Won",
				"Brazilian Real",
				"Yuan",
				"Ruble",
				"Krona",
				"Dirham",
				"Shekel",
				"Baht",
				"Rial",
				"Turkish Lira",
				"Dinar",
				"Zloty",
				"Forint",
				"Rand",
				"Vietnamese Dong",
				"Krone",
				"Ringgit",
				"Rupiah",
				"Naira",
				"Hryvnia",
				"Renminbi",
				"Sterling Pound",
				"US Dollar",
				"Canadian Dollar",
				"Aussie Dollar",
			},
		},
		{
			category:            "financial_service",
			includeRandomSuffix: true,
			inputs: []string{
				"Venmo",
				"PayPal",
				"Visa",
				"CashApp",
				"Stripe",
				"Mastercard",
				"Zelle",
				"Chase",
				"Wells Fargo",
				"Goldman Sachs",
				"American Express",
				"Amex",
				"Discover Card",
				"Bank of America",
				"HSBC",
				"Barclays",
				"Morgan Stanley",
				"BlackRock",
				"Charles Schwab",
				"Fidelity",
				"Wise Transfer",
				"Revolut",
				"Square Cash",
				"JPMorgan",
				"Citibank",
				"Deutsche Bank",
				"UBS",
				"Vanguard",
				"Western Union",
				"MoneyGram",
				"Klarna",
				"Affirm",
				"SoFi",
			},
		},
		{
			category:            "general_trademark",
			includeRandomSuffix: true,
			inputs: []string{
				"Nike",
				"Disney",
				"Coca-Cola",
				"McDonald's",
				"Adidas",
				"Ferrari",
				"Supreme",
				"Gucci",
				"Louis Vuitton",
				"Rolex",
				"Starbucks",
				"Pepsi",
				"Lego",
				"Marvel",
				"Lamborghini",
				"Porsche",
				"Rolls Royce",
				"Tiffany & Co",
				"Chanel",
				"Dior",
				"Prada",
				"Hermes",
				"Cartier",
				"Red Bull",
				"Hershey's",
				"Nestle",
				"Budweiser",
				"Heineken",
				"Jack Daniels",
				"KFC",
				"Burger King",
				"Subway",
				"Walmart",
				"Target",
				"Ikea",
				"Toyota",
				"Harley Davidson",
			},
		},
		{
			category: "government_affiliation",
			inputs: []string{
				"Federal Reserve",
				"US Treasury",
				"Official Currency",
				"Government Backed",
				"National Reserve",
				"Central Bank Coin",
				"State Issued Token",
				"Treasury Note",
				"Federal Mint",
				"SEC Approved",
				"IRS Coin",
				"FBI Token",
				"Pentagon Dollar",
				"White House Cash",
				"Department of Treasury Coin",
				"CFTC Regulated",
				"Official US Dollar",
				"Republic Reserve",
				"Presidential Dollar",
				"Congressional Cash",
				"Senate Token",
				"EU Central Bank Token",
				"Bank of England Coin",
				"Ministry of Finance",
				"Government Authorized",
				"Nationally Recognized Currency",
				"Federally Chartered Token",
				"US Mint Certified",
				"OFAC Compliant Coin",
			},
		},
		{
			category:            "impersonation",
			includeRandomSuffix: true,
			inputs: []string{
				"Bitc0in",
				"Paypall",
				"Appple",
				"G00gle",
				"Amaz0n",
				"Ethereium",
				"SoIana",
				"D0gecoin",
				"Venm0",
				"Binanse",
				"Micr0soft",
				"Teslla",
				"Net flix",
				"F8cebook",
				"Bítcoin",
				"B!tcoin",
				"Bittcoin",
				"Bitcoyn",
				"Eth3reum",
				"Ethreum",
				"Litec0in",
				"C0inbase",
				"Amzon",
				"Disnney",
				"MasterCar d",
				"V1sa",
				"Mastercar",
				"Chase Banq",
				"Krakken",
				"ByBit Exchange",
				"Solarna",
				"Doggecoin",
				"Shibaa Inu",
				"0penAI",
				"Npvidia",
				"Samsumg",
				"Micros0ft",
				"Applle Inc",
			},
		},
		{
			category: "misleading_backing",
			inputs: []string{
				"FDIC Insured Coin",
				"Gold Backed Token",
				"Guaranteed Returns",
				"Insured Deposit Coin",
				"Asset Backed Stable",
				"100% Reserved Token",
				"Bank Guaranteed Coin",
				"Principal Protected",
				"Risk Free Token",
				"Fully Collateralized USD",
				"SIPC Protected Coin",
				"Double Your Money",
				"Guaranteed 10% Yield",
				"Zero Risk Token",
				"Safe Haven Coin",
				"AAA Rated Crypto",
				"Lloyds Insured",
				"Platinum Backed",
				"Silver Backed Dollar",
				"Never Lose Token",
				"Zero Loss Guarantee",
				"Hedge Fund Coin",
				"Treasury Bond Token",
				"Investment Grade Coin",
				"Bulletproof Dollar",
				"Pegged to Gold 1:1",
				"Oil Reserve Backed",
				"Real Estate Secured Coin",
				"Diamond Backed",
				"Physically Backed Bullion",
				"Warranted Return Token",
				"Capital Preservation Guaranteed",
			},
		},
		{
			category: "platform_impersonation",
			inputs: []string{
				"FlipCa$h",
				"Flipcash Token",
				"USDF Coin",
				"F1ipcash",
				"US DF",
				"Flip Cash",
				"FlipKash",
				"USDF Reserve",
				"Flipcash Official",
				"FlipCash Gold",
				"FlipCoin",
				"Flypcash",
				"FIipcash",
				"F|ipcash",
				"USDFlip",
				"Flipcash Plus",
				"Flipcash Pro",
				"Flipcash Premium",
				"Flip-Cash",
				"USDF Token",
				"The Official Flipcash",
				"U$DF",
				"USDF+",
				"Flippcash",
				"Flipcach",
				"Flipcash v2",
				"Flipkash USD",
				"Flippcash Reserve",
				"FlipCash DAO",
				"USDFiat",
				"USDFInance",
				"Flipcash Network",
				"USDFlipcoin",
			},
		},
		{
			category:            "public_figure",
			includeRandomSuffix: true,
			inputs: []string{
				"Elon",
				"Trump",
				"Elon Musk",
				"Biden",
				"Obama",
				"Bezos",
				"Zuckerberg",
				"Taylor Swift",
				"Musk",
				"Kanye Coin",
				"Beyonce",
				"Oprah",
				"Kardashian",
				"Putin",
				"Xi Jinping",
				"King Charles",
				"Vitalik",
				"Satoshi",
				"CZ Binance",
				"Warren Buffett",
				"Bill Gates",
				"Mark Zuck",
				"Kim Kardashian",
				"Drake",
				"LeBron",
				"Messi",
				"Ronaldo",
				"Jay-Z",
				"MrBeast",
				"Rihanna",
				"Jeff Bezos",
				"Joe Rogan",
				"Zelensky",
			},
		},
		{
			category: "stablecoin",
			inputs: []string{
				"USDC",
				"USDT",
				"Tether",
				"DAI",
				"TrueUSD",
				"Pax Dollar",
				"BUSD",
				"FRAX",
				"USDP",
				"USD Coin",
				"PYUSD",
				"FDUSD",
				"USDe",
				"USDD",
				"GUSD",
				"EURC",
				"sDAI",
				"sUSD",
				"crvUSD",
				"USDY",
				"LUSD",
				"USDS",
				"RLUSD",
				"Dollar Pegged Token",
				"1:1 USD Stable",
				"Fixed Dollar Coin",
				"Stable Dollar",
				"Dollar Peg Token",
				"Digital Dollar",
				"USDJ",
				"Gemini Dollar",
				"First Digital USD",
			},
		},
		{
			category:            "tech_company",
			includeRandomSuffix: true,
			inputs: []string{
				"Apple",
				"Google",
				"Meta",
				"Amazon",
				"Microsoft",
				"Tesla",
				"Netflix",
				"Nvidia",
				"Samsung",
				"Intel",
				"Oracle",
				"IBM",
				"Salesforce",
				"Adobe",
				"SpaceX",
				"OpenAI",
				"Anthropic",
				"Uber",
				"Airbnb",
				"Spotify",
				"Qualcomm",
				"Cisco Systems",
				"Dell",
				"Hewlett Packard",
				"Sony",
				"AMD",
				"Facebook",
				"Twitter",
				"TikTok",
				"Snapchat",
				"LinkedIn",
				"Alphabet Inc",
				"Alibaba",
				"Tencent",
				"Baidu",
				"ByteDance",
				"Palantir",
				"Snowflake",
				"Databricks",
			},
		},
	}

	for _, tt := range tests {
		for _, input := range tt.inputs {
			if tt.includeRandomSuffix {
				suffixes := []string{
					"Token",
					"Tokens",
					"Cash",
					"Money",
					"Dollar",
					"Dollars",
					"Coin",
				}
				input = fmt.Sprintf("%s %s", input, suffixes[rand.IntN(len(suffixes))])
			}
			t.Run(tt.category+"/"+input, func(t *testing.T) {
				result, err := client.ClassifyCurrencyName(ctx, input)
				require.NoError(t, err)

				assert.True(t, result.Flagged, "expected %q to be flagged (scores: %v)", input, result.CategoryScores)
			})
		}
	}
}

func TestClassifyCurrencyName_AllCategoriesPresent(t *testing.T) {
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		t.Fatal("ANTHROPIC_API_KEY environment variable is required")
	}

	client := NewClient(apiKey)
	ctx := context.Background()

	expectedCategories := []string{
		"cryptocurrency",
		"exchange_platform",
		"fiat_currency",
		"financial_service",
		"general_trademark",
		"government_affiliation",
		"impersonation",
		"misleading_backing",
		"platform_impersonation",
		"public_figure",
		"stablecoin",
		"tech_company",
	}

	result, err := client.ClassifyCurrencyName(ctx, "FunkyToken")
	require.NoError(t, err)

	for _, category := range expectedCategories {
		_, ok := result.CategoryScores[category]
		assert.True(t, ok, "missing category %q in response scores", category)
	}
}

func TestClassifyCurrencyName_SafeNameNotFlagged(t *testing.T) {
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		t.Fatal("ANTHROPIC_API_KEY environment variable is required")
	}

	client := NewClient(apiKey)
	ctx := context.Background()

	safeNames := []string{
		"Jeffy",
		"Teddies",
		"Cattle Cash",
		"bmoney",
		"Ducat",
		"Panda",
		"LANDO",
		"Tones",
		"Walrus",
		"Moony",
		"XP",
		"Bits",
		"Float",
		"Bogey",
		"Market Coin",
	}

	for _, name := range safeNames {
		t.Run(name, func(t *testing.T) {
			result, err := client.ClassifyCurrencyName(ctx, name)
			require.NoError(t, err)

			assert.False(t, result.Flagged,
				"expected %q to not be flagged, flagged categories: %v (scores: %v)",
				name, result.FlaggedCategories, result.CategoryScores)
		})
	}
}
